Dashboard SignUp Page
OscuroBok/OscuroBok_dashboard_FE pull request #2
Opened 2024-08-14 15:42 UTC by abir446

Sign up page as per the figma design. It uses react-hook-form.

2024-08-15 12:15 UTC, arka1997 submitted a review, later dismissed
Looks good

2024-08-15 21:20 UTC, Kaustav2000 commented on src/pages/auth/sign-up.jsx
> +            <option value="superAdin" className="text-[#D1293D] text-[14px] font-[500]">Super Admin</option>
Please fix this "superAdin"

2024-08-15 21:32 UTC, Kaustav2000 requested changes
Please do the required changes

2024-08-15 21:32 UTC, Kaustav2000 commented on src/pages/auth/sign-up.jsx
> +          <select
Increase the height and add some border radius to the dropdown menu as well as line-spaces

2024-08-15 21:32 UTC, Kaustav2000 commented on src/pages/auth/sign-up.jsx
Adjust the Proportion of Sign up form. Reduce the form size till 60%
![image](https://github.com/user-attachments/assets/9e65db7e-7b0d-4511-b849-f00ed587a5e1)

Reduce the size  of error text so that form size remains intact
![image](https://github.com/user-attachments/assets/fa17c5d0-888e-4ebb-89b8-b81a38e6ca39)

2024-08-16 05:17 UTC, abir446 commented on src/pages/auth/sign-up.jsx
> +            <option value="superAdin" className="text-[#D1293D] text-[14px] font-[500]">Super Admin</option>
Fixed this issue.

2024-08-16 06:18 UTC, abir446 commented on src/pages/auth/sign-up.jsx
I reduced the text size, and also reduced the gap between input and error message.

2024-08-16 06:20 UTC, abir446 commented on src/pages/auth/sign-up.jsx
> +          <select
![image](https://github.com/user-attachments/assets/96eb3727-38c8-43e7-a220-d9aa6c59bc62)
increased the text size of the elements so that the height looks larger, however, I couldn't find a way to give spaces between the lines.

2024-08-17 16:39 UTC, Kaustav2000 approved these changes
Looks good to me

2024-08-18 09:36 UTC, arka1997 approved these changes

2024-08-18 09:37 UTC, merged